Make the vault fully async and fix the Vault Test suite to work with async/await.
maidsafe/safe-vault pull request #1103
Opened 2020-09-17 10:20 UTC by lionel1704

2020-09-17 11:06 UTC, joshuef requested changes

2020-09-17 11:06 UTC, joshuef commented on Cargo.toml
> +#safe_core = { git = "https://github.com/maidsafe/safe_client_libs", branch = "master" }
```suggestion
safe_core = { git = "https://github.com/maidsafe/safe_client_libs", branch = "master" }
```

2020-09-17 11:06 UTC, joshuef commented on Cargo.toml
> +safe_core = { path = "../safe_client_libs" }
```suggestion
#safe_core = { path = "../safe_client_libs" }
```

2020-09-17 20:20 UTC, Yoga07 approved these changes

2020-09-18 08:57 UTC, joshuef requested changes
Would be good for this to work with network launcher tool before merging.

We really need to stick to one method of bootstrapping a network, and I view that as our goto. If we need changes from any other script we should be incorporating them there

2020-09-18 09:16 UTC, joshuef commented on src/chunk_store/tests.rs
> +        let used_space_before = used_space.lock().unwrap();
@lionel1704 I don't think we should be adding in all these `unwraps` given we've been trying to remove them recently.

Better to be using `futures::lock::Mutex` and then this will look like `used_space.lock().await`, no `unwrap()` needed 👍

2020-09-21 05:48 UTC, lionel1704 commented
Superseeded by #1106

2020-09-21 05:48 UTC, closed without merging